/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.Aluno;
import Controle.ControleAluno;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelListener;
import static Visao.ControladorPrincipal.listaDeAlunos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adriano
 */
public class Cadastro_Aluno extends javax.swing.JPanel {
    
    ControleAluno acessoAluno = new ControleAluno();
    /**
     * Creates new form Cadastro_Aluno
     */
    public Cadastro_Aluno() {
        
            initComponents();
            acessoAluno.listarAluno();
           preencherTabela();
           
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldData = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAtalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAluno = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Aluno");

        jLabel2.setText("CPF");

        jLabel3.setText("Endereco");

        jLabel4.setText("Data de Entrada");

        jLabel5.setText("Senha");

        jLabel6.setText("Login");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonPrimeiro.setText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonUltimo.setText("Ultimo");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonProximo.setText("Proximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAtalizar.setText("Atualizar");
        jButtonAtalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtalizarActionPerformed(evt);
            }
        });

        jTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCadastrar)
                                    .addComponent(jButtonPrimeiro)
                                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonUltimo))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonProximo)
                                                .addGap(29, 29, 29)
                                                .addComponent(jButtonAnterior))
                                            .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButtonAtalizar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)))
                                .addGap(138, 138, 138)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldData, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonVoltar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonAnterior))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAtalizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        String cpf = jTextFieldCPF.getText();
        String data = jTextFieldData.getText();
        String endereco = jTextFieldEndereco.getText();
        String login = jTextFieldLogin.getText();
        String senha = jPasswordField.getText();
        
        Aluno novoAluno = new Aluno(login, cpf, endereco, data, senha);
        try {
            acessoAluno.insertAluno(novoAluno);
        } catch (Exception e) {
            
        }
        
        jTextFieldCPF.setText("");
        jTextFieldData.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldLogin.setText("");
        jPasswordField.setText("");
        
        JOptionPane.showMessageDialog(null, "Aluno Cadastrado");
        preencherTabela();
        ControladorPrincipal.janela.setContentPane(ControladorPrincipal.cadastroAluno);
        ControladorPrincipal.janela.setVisible(true);
        
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        ControladorPrincipal.janela.setContentPane(ControladorPrincipal.menuAluno);
        ControladorPrincipal.janela.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        try{
        acessoAluno.result.first();
        
        jTextFieldCPF.setText(acessoAluno.result.getString("cpf"));
        jTextFieldData.setText(acessoAluno.result.getString("dt_cadastro"));
        jTextFieldEndereco.setText(acessoAluno.result.getString("endereco"));
        jTextFieldLogin.setText(acessoAluno.result.getString("login"));
        jPasswordField.setText(acessoAluno.result.getString("senha"));
        
        if(acessoAluno.result.isFirst()){
                jButtonPrimeiro.setEnabled(true);
                jButtonAnterior.setEnabled(true);
        }
        
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        try{
        acessoAluno.result.last();
        jTextFieldCPF.setText(acessoAluno.result.getString("cpf"));
        jTextFieldData.setText(acessoAluno.result.getString("dt_cadastro"));
        jTextFieldEndereco.setText(acessoAluno.result.getString("endereco"));
        jTextFieldLogin.setText(acessoAluno.result.getString("login"));
        jPasswordField.setText(acessoAluno.result.getString("senha"));
        
        if(acessoAluno.result.isLast()){
                jButtonUltimo.setEnabled(true);
                jButtonProximo.setEnabled(true);
        }
        
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        try{
        acessoAluno.result.next();
        jTextFieldCPF.setText(acessoAluno.result.getString("cpf"));
        jTextFieldData.setText(acessoAluno.result.getString("dt_cadastro"));
        jTextFieldEndereco.setText(acessoAluno.result.getString("endereco"));
        jTextFieldLogin.setText(acessoAluno.result.getString("login"));
        jPasswordField.setText(acessoAluno.result.getString("senha"));
        if(acessoAluno.result.isLast()){
            jButtonProximo.setEnabled(false);
            jButtonAnterior.setEnabled(true);
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        try{
        acessoAluno.result.previous();
        jTextFieldCPF.setText(acessoAluno.result.getString("cpf"));
        jTextFieldData.setText(acessoAluno.result.getString("dt_cadastro"));
        jTextFieldEndereco.setText(acessoAluno.result.getString("endereco"));
        jTextFieldLogin.setText(acessoAluno.result.getString("login"));
        jPasswordField.setText(acessoAluno.result.getString("senha"));
        if(acessoAluno.result.isFirst()){
            jButtonAnterior.setEnabled(false);
            jButtonProximo.setEnabled(true);
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonAtalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtalizarActionPerformed
        // TODO add your handling code here:
        String cpf = jTextFieldCPF.getText();
        String data = jTextFieldData.getText();
        String endereco = jTextFieldEndereco.getText();
        String login = jTextFieldLogin.getText();
        String senha = jPasswordField.getText();
        
        Aluno novoAluno = new Aluno(login, cpf, endereco, data, senha);
        try {
            acessoAluno.atualizaAluno(novoAluno);
            
        } catch (Exception e) {
            
        }
        
        jTextFieldCPF.setText("");
        jTextFieldData.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldLogin.setText("");
        jPasswordField.setText("");
        
        JOptionPane.showMessageDialog(null, "Aluno Atualizado");
    }//GEN-LAST:event_jButtonAtalizarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        String cpf = jTextFieldCPF.getText();
        String data = jTextFieldData.getText();
        String endereco = jTextFieldEndereco.getText();
        String login = jTextFieldLogin.getText();
        String senha = jPasswordField.getText();
        
        Aluno novoAluno = new Aluno(login, cpf, endereco, data, senha);
        try {
            acessoAluno.excluirAluno(novoAluno);
            
        } catch (Exception e) {
            
        }
        
        jTextFieldCPF.setText("");
        jTextFieldData.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldLogin.setText("");
        jPasswordField.setText("");
        
        JOptionPane.showMessageDialog(null, "Aluno Excluido");
    }//GEN-LAST:event_jButtonExcluirActionPerformed
 public void preencherTabela(){
     
     ArrayList dados = new ArrayList();
     String[] colunas = {"CPF", "Endereço", "Data", "Login"};
     try{
     while(acessoAluno.result.next()){
         dados.add(new Object[]{acessoAluno.result.getString("cpf"),
         acessoAluno.result.getString("endereco"),
         acessoAluno.result.getString("dt_cadastro"),
         acessoAluno.result.getString("login")});
     }
     
     }
     catch(Exception e){
         
     }
     ModeloTabela modelo = new ModeloTabela(dados, colunas);
     jTableAluno.setModel(modelo);
 }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAtalizar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAluno;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
